CREATE TABLE rides (
    booking_id TEXT PRIMARY KEY,
    booking_time TEXT,
    booking_status TEXT,
    customer_id TEXT,
    vehicle_type TEXT,
    pickup_location TEXT,
    drop_location TEXT,
    vendor_tat REAL,
    customer_tat REAL,
    cancelled_by_customer_reason TEXT,
    cancelled_by_driver_reason TEXT,
    incomplete_flag TEXT,
    incomplete_reason TEXT,
    booking_value REAL,
    payment_method TEXT,
    ride_distance REAL,
    driver_rating REAL,
    customer_rating REAL,
    vehicle_image TEXT,
    is_completed INTEGER,
    is_cancelled INTEGER,
    hour_of_day INTEGER,
    weekday TEXT
);